productName: vesta
componentName: vestafe

stages:
  build: yes

build:
  buildFlow:
  buildTool:
  buildToolVersion:
  buildEnvironment:
  buildOptionString:
  buildAntOpts: 
  mavenSettings: 

jobsToCopyFromList: 
 
targetDir: 

artifactsToArchive: 

builds_to_execute:
  vestafe:
    artifactsToPublish:
